# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!

# the path to your blog's icon:
favicon: /source/icon_img/blog_browser_logo.jpg

# the path to manifest.json
manifest: /manifest.json

# [Open Graph Protocol](https://ogp.me/)
og_enabled: true
og_image: /favicon.png
og:
  # customize og properties here which will replace the defaults

# show excerpt on post list
show_excerpt: false

# light/dark/auto color scheme
color_scheme: auto

# show floating color theme toggle
show_color_scheme_toggle: true

# uppercase categories
uppercase_categories: true

# capitalize tag names on tags page
capitalize_tags: false

# add hashtag prefix before tags
hashtag_prefix_before_tags: true

# rainbow!
rainbow_banner: true
rainbow_banner_colors:
  - '#e50000'
  - '#ff8d00'
  - '#ffee00'
  - '#008121'
  - '#004cff'
  - '#760188'
# choose from [auto, always]
rainbow_banner_shown: auto
# Pride Month by default
rainbow_banner_month: 6

# # TOC - table of contents
# toc:
#   enable: true
#   # Automatically add list number to toc
#   number: true
#   # If true, all word will placed on next lines if header width longer then sidebar width
#   wrap: true
#   # If true, all level of TOC in a post will be displayed, rather than the activated part of it
#   expand_all: false
#   # Maximum heading depth of generated TOC
#   _max_depth: 2

# scroll reveal (https://scrollrevealjs.org/) - animating elements as they enter/leave the viewport
scroll_reveal: true

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Blog
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Connections: /connections
    Projects: /projects
    About: /about
    # these will be automatically be an icon
    GitHub: https://github.com/kevinchiu923
    LinkedIn: https://www.linkedin.com/in/yen-ming-kevin-chiu/
    # CodePen: https://codepen.io/mrwillcom
    # Patreon: https://www.patreon.com/MrWillCom
    # Mastodon: https://noc.social/@MrWillCom
    # Discord: https://discord.gg/UKuFDjcfY8
    Search: /search

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    Blog: /
    Archives: /archives
    Tags: /tags
    Categories: /categories
    Search: /search
    Connections: /connections
    Projects: /projects
    Resume: /resume
    About: /about
    RSS: /atom.xml
  # also the title
  Projects:
    # the items
    # RSA CLI: https://github.com/MrWillCom/rsa-cli
    # Hexo Theme Cupertino: https://github.com/MrWillCom/hexo-theme-cupertino
    # A Calendar: https://github.com/MrWillCom/a-calendar
    # Auto Mirroring Bucket: https://github.com/MrWillCom/auto-mirroring-bucket
  # the title
  Me:
    # items
    GitHub: https://github.com/kevinchiu923
    # CodePen: https://codepen.io/mrwillcom
    # Patreon: https://www.patreon.com/MrWillCom
    # Mastodon: https://noc.social/@MrWillCom
    # Discord: https://discord.gg/UKuFDjcfY8
    LinkedIn: https://www.linkedin.com/in/yen-ming-kevin-chiu/
    Email: mailto:kevinchiu923@gmail.com

# footer extra description
# footer_extra_description: something will be shown at the bottom of the footer

# the license your posts under
license: CC BY-NC 4.0
# the link of your license
license_link: https://creativecommons.org/licenses/by-nc/4.0

# search
# based on [hexo-generator-search](https://github.com/wzpan/hexo-generator-search)
search: true
search_path: search.json

# Enable or disable the RSS feed.
# RSS feed
feed:
  type: atom
  path: atom.xml
  limit: 0 # 最大文章數量
  content: false # 是否顯示內文
